[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pathfinding-visualizer"
version = "1.0.0"
description = "A tool to visualize pathfinding algorithms."
authors = [
    {name = "Rudransh Kumar"}
]
requires-python = ">=3.10"
dependencies = [
    "pygame",
    "numpy",
]